GET http://localhost:3000/books/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNzMxMTQyNTAyfQ.rHjHUZPyxPzlOZ0Ixz_tDiCBeb2crncd0JRG9TsGfrg

###

GET http://localhost:3000/books/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNzMxMTQyNTAyfQ.rHjHUZPyxPzlOZ0Ixz_tDiCBeb2crncd0JRG9TsGfrg

###

GET http://localhost:3000/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNzMxMTQyNTAyfQ.rHjHUZPyxPzlOZ0Ixz_tDiCBeb2crncd0JRG9TsGfrg
###

POST http://localhost:3000/users/
Content-Type: application/json

{    
    "username": "rahul123",
    "password": "rahul@456",
    "gender":"male",
    "location":"hyderabad"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{    
    "username": "rahul123",
    "password": "rahul@456"
}



###my

POST http://localhost:3000/users/
Content-Type: application/json

{    
    "username": "madhu",
    "password": "madhu12",
    "gender":"male",
    "location":"biccavolu"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{    
    "username": "madhu",
    "password": "madhu12"
}

GET http://localhost:3000/books/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZGh1IiwiaWF0IjoxNzMxMTQzNDA4fQ.B4vIYfH7boaaw6wj_3wRo9LxkSXlwpLIkMe7jJkhi_o

###

GET http://localhost:3000/books/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZGh1IiwiaWF0IjoxNzMxMTQzNDA4fQ.B4vIYfH7boaaw6wj_3wRo9LxkSXlwpLIkMe7jJkhi_o

###
GET http://localhost:3000/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZGh1IiwiaWF0IjoxNzMxMTQzNDA4fQ.B4vIYfH7boaaw6wj_3wRo9LxkSXlwpLIkMe7jJkhi_o
